# Generated by Django 3.0 on 2019-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='tag',
            field=models.ManyToManyField(to='newsletters.Tags'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
